_commit: v0.4.1
_src_path: https://github.com/will-rice/papers-template.git
project_name: ASR Papers
project_slug: asr-papers
template_version: 0.1.0
topic_description: A curated, automatically-updated collection of ASR papers with
    an LLM-friendly markdown corpus.
